// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMYl_wJOgx33_wD3jFrxce8D7wUWcz-js',
    appId: '1:990853550319:web:a8651b79d41e62e11ecb1a',
    messagingSenderId: '990853550319',
    projectId: 'retailerapp-c3a82',
    authDomain: 'retailerapp-c3a82.firebaseapp.com',
    storageBucket: 'retailerapp-c3a82.appspot.com',
    measurementId: 'G-V04L33SBY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ3azAdmVZh4FPWOODtzjcMK1g-QPC58Q',
    appId: '1:990853550319:android:8ea27b0d1a0cc9211ecb1a',
    messagingSenderId: '990853550319',
    projectId: 'retailerapp-c3a82',
    storageBucket: 'retailerapp-c3a82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4bz96giokYys50Y6VzBh0yfiaWfp-Wcs',
    appId: '1:990853550319:ios:90f12b1fdbe97df61ecb1a',
    messagingSenderId: '990853550319',
    projectId: 'retailerapp-c3a82',
    storageBucket: 'retailerapp-c3a82.appspot.com',
    iosClientId: '990853550319-3fp8o8bs5mg4ng53rbip3vm0jbjmpnt1.apps.googleusercontent.com',
    iosBundleId: 'com.example.sanjuRetailerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4bz96giokYys50Y6VzBh0yfiaWfp-Wcs',
    appId: '1:990853550319:ios:90f12b1fdbe97df61ecb1a',
    messagingSenderId: '990853550319',
    projectId: 'retailerapp-c3a82',
    storageBucket: 'retailerapp-c3a82.appspot.com',
    iosClientId: '990853550319-3fp8o8bs5mg4ng53rbip3vm0jbjmpnt1.apps.googleusercontent.com',
    iosBundleId: 'com.example.sanjuRetailerApp',
  );
}
